#!/usr/bin/env bash
set -e

docker build -t rocdev_nginx infrastructure/nginx
docker rmi rocdev_nginx

docker run \
  --rm \
  -it \
  -v "$PWD"/infrastructure/terraform:/tf \
  -w '/tf' \
  hashicorp/terraform:0.10.7 \
  init
docker run \
  --rm \
  -it \
  -v "$PWD"/infrastructure/terraform:/tf \
  -w '/tf' \
  hashicorp/terraform:0.10.7 \
  fmt -check

docker run --rm -it -v "$PWD"/app:/app -w '/app' elixir:1.5.2 ./elixir_build
docker run --rm -it -v "$PWD"/app:/app -w '/app' node:8.6.0 ./node_build
