#!/usr/bin/env bash
set -e

./elixir_build
./node_build

while ! docker run --rm -it --network host postgres \
        pg_isready -h localhost -p 5432 -U postgres
do
  echo 'waiting for pg'
  sleep 1
done

mkdir -p priv/repo/migrations
mix ecto.create
mix ecto.migrate
iex -S mix phx.server
